<?php

namespace Tests\Feature\Warehouse;

use App\Models\User;
use App\Warehouse\Domain\Orders\Order;
use App\Warehouse\Domain\Orders\OrderLine;
use App\Warehouse\Domain\Products\Product;
use App\Warehouse\Domain\Repositories\OrderRepositoryInterface;
use App\Warehouse\Domain\Services\InventoryServiceInterface;
use App\Warehouse\Infrastructure\Persistence\InMemory\Repositories\InMemoryCollectionBackorderRepository;
use App\Warehouse\Infrastructure\Persistence\InMemory\Repositories\InMemoryCollectionOrderRepository;
use App\Warehouse\Infrastructure\Persistence\InMemory\Repositories\InMemoryCollectionPicklistRepository;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Mockery\MockInterface;
use Tests\TestCase;

class CancelPicklistTest extends TestCase
{
    use DatabaseMigrations;
    use RefreshDatabase;

    protected int $tenantId;
    protected InMemoryCollectionOrderRepository $orderRepository;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->user = User::factory()->create();
        $this->tenantId = $this->user->tenant_id;
        $this->actingAs($this->user);

        $this->orderRepository = new InMemoryCollectionOrderRepository();
        $this->app->instance(OrderRepositoryInterface::class, $this->orderRepository);

    }

    /** @test */
    public function it_should_increase_stock_of_order_lines_of_picklist_and_remove_picklist()
    {
        $this->withoutExceptionHandling();

        // Given
        $orderLine = new OrderLine(new Product('Test Product Code'), 10);
        $orderLines = collect(array($orderLine));

        $inventoryServiceMock = $this->mock(InventoryServiceInterface::class, function (MockInterface $mock) use ($orderLines) {
            $mock->shouldReceive('getStock')
                ->andReturn(99999);

            $mock->shouldReceive('adjustStock')
                ->times($orderLines->count())
                ->andReturnTrue();
        });

        $this->app->bind(InventoryServiceInterface::class, function () use ($inventoryServiceMock) {return $inventoryServiceMock;});

        $order = Order::factory()->make([
            'tenant_id' => $this->tenantId,
            'order_lines' => $orderLines
        ]);

        $picklist = $order->createPicklist($order->orderLines());

        $this->orderRepository->save($order);


        $url = route('cancel-picklist', [
            "picklistId" => $picklist->reference(),
        ]);

        // When
        $response = $this->post($url, [
            "Accept" => "application/json"
        ]);

        // Then
        $order = $this->orderRepository->findOneByReferenceAndTenantId($order->reference(), $order->tenantId());

        self::assertEquals(0, $order->picklists()->count());
    }
}
