<?php

namespace Tests\Feature\Warehouse;

use App\Models\User;
use App\Warehouse\Domain\Orders\Order;
use App\Warehouse\Domain\Repositories\OrderRepositoryInterface;
use App\Warehouse\Infrastructure\Persistence\InMemory\Repositories\InMemoryCollectionOrderRepository;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Mockery\MockInterface;
use Tests\TestCase;

class CreateOrderTest extends TestCase
{
    use DatabaseMigrations;
    use RefreshDatabase;

    protected InMemoryCollectionOrderRepository $orderRepository;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->user = User::factory()->create();
        $this->actingAs($this->user);
        $this->tenantId = $this->user->tenant_id;

        $this->orderRepository = new InMemoryCollectionOrderRepository();
        $this->app->bind(OrderRepositoryInterface::class, function () {return $this->orderRepository;});
    }

    /** @test */
    public function it_should_create_an_order()
    {
        $this->withoutExceptionHandling();

        // Given
        $order = Order::factory()->make();

        $url = route('create-order');

        $input = collect($order->toArray());
        $input['order_lines'] = collect($input['order_lines'])
                                    ->map(function (array $orderLine) {
                                        return [
                                            'product_code' => $orderLine['product_code'],
                                            'quantity' => $orderLine['quantity']
                                        ];
                                    })->toArray();

        $input = $input->all();

        // When
        $response = $this->post($url, $input
        , [
            "Accept" => "application/json"
        ]);

        // Then
        $response->assertJson([
            "data" => null
        ]);

        $foundOrder = $this->orderRepository->findOneByReferenceAndTenantId($order->reference(), $this->tenantId);

        self::assertEquals($order->reference(), $foundOrder->reference());

    }

    /** @test */
    public function it_should_show_error_when_creating_order_with_same_reference()
    {
        // Given
        $orderReference = "Test Order Reference";
        $order = Order::factory()->make([
            "reference" => $orderReference,
        ]);

        // When
        $orderRepositoryMock = $this->mock(InMemoryCollectionOrderRepository::class, function (MockInterface $mock) use ($order) {
            $mock->shouldReceive('findOneByReferenceAndTenantId')
                 ->once()
                 ->andReturn($order);
        });

        $this->app->instance(OrderRepositoryInterface::class, $orderRepositoryMock);

        $url = route('create-order');

        $input = collect($order->toArray());
        $input['order_lines'] = collect($input['order_lines'])
            ->map(function (array $orderLine) {
                return [
                    'product_code' => $orderLine['product_code'],
                    'quantity' => $orderLine['quantity']
                ];
            })->toArray();

        $input = $input->all();

        // When
        $response = $this->post($url, $input, [
            "Accept" => "application/json"
        ]);

        // Then
        $response->assertJson([
            "data" => null,
            "error" =>  "Order with reference " . $orderReference . " already exists"
        ]);
    }
}
