<?php

namespace Tests\Feature\Warehouse;

use App\Models\User;
use App\Warehouse\Domain\Orders\Order;
use App\Warehouse\Domain\Repositories\OrderRepositoryInterface;
use App\Warehouse\Infrastructure\Persistence\InMemory\Repositories\InMemoryCollectionBackorderRepository;
use App\Warehouse\Infrastructure\Persistence\InMemory\Repositories\InMemoryCollectionOrderRepository;
use App\Warehouse\Infrastructure\Persistence\InMemory\Repositories\InMemoryCollectionPicklistRepository;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class GetAllBackordersTest extends TestCase
{
    use DatabaseMigrations;
    use RefreshDatabase;

    protected InMemoryCollectionPicklistRepository $picklistRepository;
    protected InMemoryCollectionOrderRepository $orderRepository;
    protected int $tenantId;
    protected User $user;
    protected InMemoryCollectionBackorderRepository $backorderRepository;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->user = User::factory()->create();
        $this->tenantId = $this->user->tenant_id;
        $this->actingAs($this->user);

        $this->orderRepository = new InMemoryCollectionOrderRepository();
        $this->app->bind(OrderRepositoryInterface::class, function() {return $this->orderRepository;});
    }

    /** @test */
    public function it_should_return_all_backorders_for_tenant()
    {
        // Given
        $order = Order::factory()->make([
            'tenant_id' => $this->tenantId
        ]);

        $order->createBackorder($order->orderLines());

        $this->orderRepository->save($order);

        $url = route('get-all-backorders');

        // When
        $response = $this->get($url);

        // Then
        $response->assertJson([
            'data' => $order->backorders()->toArray()
        ]);
    }
}
