<?php

namespace Tests\Feature\Warehouse;

use App\Models\User;
use App\Warehouse\Domain\Orders\Order;
use App\Warehouse\Domain\Repositories\OrderRepositoryInterface;
use App\Warehouse\Infrastructure\Persistence\InMemory\Repositories\InMemoryCollectionOrderRepository;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class GetAllOrdersTest extends TestCase
{
    use DatabaseMigrations;
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->user = User::factory()->create();
        $this->actingAs($this->user);
        $this->tenantId = $this->user->tenant_id;
        $this->token = $this->user->createToken('bearer')
                    ->plainTextToken;

        $this->orderRepository = new InMemoryCollectionOrderRepository();
        $this->app->instance(OrderRepositoryInterface::class, $this->orderRepository);
    }

    /** @test */
    public function it_should_return_all_orders_that_belong_to_tenant()
    {
        $this->withoutExceptionHandling();

        // Given
        $ordersOfTenant = Order::factory(2)->make([
            "tenant_id" => $this->tenantId,
        ]);

        $ordersOfOtherTenant = Order::factory(2)->make([
            "tenant_id" => $this->tenantId + 1,
        ]);

        $this->orderRepository->saveMultiple($ordersOfTenant);
        $this->orderRepository->saveMultiple($ordersOfOtherTenant);

        $url = route('get-all-orders');

        // When
        $response = $this->get($url, [
            "Accept" => "application/json",
            "Authorization" => "Bearer " . $this->token
        ]);

        $ordersOfTenantAsArray = $ordersOfTenant->toArray();

        // Then
        $response->assertJson([
            "data" => $ordersOfTenantAsArray
        ]);
    }
}
