<?php

namespace Tests\Feature\Warehouse;

use App\Models\User;
use App\Warehouse\Domain\Orders\Order;
use App\Warehouse\Domain\Repositories\OrderRepositoryInterface;
use App\Warehouse\Infrastructure\Persistence\InMemory\Repositories\InMemoryCollectionBackorderRepository;
use App\Warehouse\Infrastructure\Persistence\InMemory\Repositories\InMemoryCollectionOrderRepository;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class GetBackordersForOrderTest extends TestCase
{
    use DatabaseMigrations;
    use RefreshDatabase;

    protected int $tenantId;
    protected InMemoryCollectionOrderRepository $orderRepository;
    protected InMemoryCollectionBackorderRepository $backorderRepository;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->user = User::factory()->create();
        $this->tenantId = $this->user->tenant_id;
        $this->actingAs($this->user);

        $this->orderRepository = new InMemoryCollectionOrderRepository();

        $this->app->bind(OrderRepositoryInterface::class, function () {return $this->orderRepository;});
    }

    /** @test */
    public function it_should_return_backorders_for_order()
    {
        // Given
        $order = Order::factory()->make([
            'tenant_id' => $this->tenantId
        ]);

        $order->createBackorder($order->orderLines());
        $this->orderRepository->save($order);

        $url = route('get-backorders-for-order', [
            'orderReference' => $order->reference()
        ]);

        // When
        $response = $this->get($url);

        // Then
        $response->assertJson([
            'data' => $order->backorders()->toArray()
        ]);
    }

    /** @test */
    public function it_should_return_404_when_order_with_reference_does_not_exist()
    {
        // Given
        $orderReference = "Unknown Order Reference";

        $url = route('get-backorders-for-order', [
            'orderReference' => $orderReference
        ]);

        // When
        $response = $this->get($url);

        // Then
        $response->assertStatus(404);
        $response->assertJson([
            'error' => [
                'code' => 2,
                'message' => 'Order with reference ' . $orderReference . ' not found'
            ]
        ]);
    }
}
