<?php

namespace Feature\Warehouse;

use App\Models\User;
use App\Warehouse\Domain\Orders\Order;
use App\Warehouse\Domain\Repositories\OrderRepositoryInterface;
use App\Warehouse\Infrastructure\Persistence\InMemory\Repositories\InMemoryCollectionOrderRepository;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class GetOrderByReferenceTest extends TestCase
{
    use DatabaseMigrations;
    use RefreshDatabase;

    protected InMemoryCollectionOrderRepository $orderRepository;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->orderRepository = new InMemoryCollectionOrderRepository();
        $this->app->bind(OrderRepositoryInterface::class, function () {return $this->orderRepository;});
        $this->user = User::factory(1)->makeOne();
        $this->actingAs($this->user);
    }

    /** @test */
    public function it_should_return_order_by_reference()
    {
        // Given
        $order = Order::factory(1)->makeOne([
            'tenant_id' => $this->user->tenant->id
        ]);

        $url = route('get-order-by-reference', [
            'orderReference' => $order->reference()
        ]);

        $this->orderRepository->save($order);

        // When
        $response = $this->get($url);

        // Then
        $response->assertOk();
        $response->assertJson([
            'data' => $order->toArray()
        ]);
    }

    /** @test */
    public function it_should_return_error_when_order_not_found()
    {
        // Given
        $orderReference = 'Non Existing Order Reference';
        $url = route('get-order-by-reference', [
            'orderReference' => $orderReference
        ]);

        // When
        $response = $this->get($url);

        // Then
        $response->assertStatus(404);
        $response->assertJson([
            'error' => [
                'code' => 1,
                'message' => 'Order with reference ' . $orderReference . ' not found'
            ]
        ]);
    }
}
