<?php

namespace Tests\Feature\Warehouse;

use App\Models\User;
use App\Warehouse\Domain\Orders\Order;
use App\Warehouse\Domain\Repositories\OrderRepositoryInterface;
use App\Warehouse\Infrastructure\Persistence\InMemory\Repositories\InMemoryCollectionOrderRepository;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class PickAllProductsFromPicklist extends TestCase
{
    use DatabaseMigrations;
    use RefreshDatabase;

    protected int $tenantId;
    protected InMemoryCollectionOrderRepository $orderRepository;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->user = User::factory()->create();
        $this->tenantId = $this->user->tenant_id;
        $this->actingAs($this->user);

        $this->orderRepository = new InMemoryCollectionOrderRepository();
        $this->app->instance(OrderRepositoryInterface::class, $this->orderRepository);

    }

    /** @test */
    public function it_should_update_amount_picked()
    {
        // Given
        $this->withoutExceptionHandling();
        $order = Order::factory()->make([
            'tenant_id' => $this->tenantId
        ]);

        $picklist = $order->createPicklist($order->orderLines());
        $this->orderRepository->save($order);

        $url = route('pick-all-products-from-picklist', [
            'picklistId' => $picklist->reference()
        ]);

        // When
        $response = $this->post($url);

        // Then
        $foundOrder = $this->orderRepository->findOneByReferenceAndTenantId($order->reference(), $this->tenantId);
        $picklist = $foundOrder->picklists()->first();

        self::assertTrue($picklist->fullyPicked());

        $response->assertJson([
            'data' => $picklist->toArray()
        ]);
    }

    /** @test */
    public function it_should_return_404_error_when_picklist_not_found()
    {
        // Given
        $order = Order::factory()->make([
            'tenant_id' => $this->tenantId
        ]);

        $this->orderRepository->save($order);

        $picklistId = 'Non Existing Picklist Id';

        $url = route('pick-all-products-from-picklist', [
            'picklistId' => $picklistId
        ]);

        // When
        $response = $this->post($url);

        // Then
        $response->assertStatus(404);
        $response->assertJson([
            'error' => [
                'message' => 'Picklist with id or reference ' . $picklistId . ' not found',
                'code' => 1
            ]
        ]);
    }
}
