<?php

namespace Tests\Feature\Warehouse;

use App\Models\User;
use App\Warehouse\Domain\Orders\Order;
use App\Warehouse\Domain\Repositories\OrderRepositoryInterface;
use App\Warehouse\Domain\Services\InventoryServiceInterface;
use App\Warehouse\Infrastructure\Persistence\InMemory\Repositories\InMemoryCollectionBackorderRepository;
use App\Warehouse\Infrastructure\Persistence\InMemory\Repositories\InMemoryCollectionOrderRepository;
use App\Warehouse\Infrastructure\Persistence\InMemory\Repositories\InMemoryCollectionPicklistRepository;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Mockery\MockInterface;
use Tests\TestCase;

class ProcessBackordersTest extends TestCase
{
    use DatabaseMigrations;
    use RefreshDatabase;

    protected int $tenantId;
    protected OrderRepositoryInterface $orderRepository;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->user = User::factory()->create();
        $this->tenantId = $this->user->tenant_id;
        $this->actingAs($this->user);

        $this->orderRepository = new InMemoryCollectionOrderRepository();
        $this->app->bind(OrderRepositoryInterface::class, function () {return $this->orderRepository;});
    }

    /** @test */
    public function it_should_convert_backorder_to_picklist_if_product_on_stock()
    {
        // Given
        $this->withoutExceptionHandling();
        $inventoryServiceMock = $this->mock(InventoryServiceInterface::class, function (MockInterface $mock) {
            $mock->shouldReceive('getStock')
                ->andReturn(99999999);
        });

        $order = Order::factory()->make([
            'tenant_id' => $this->tenantId,
            'inventory_service' => $inventoryServiceMock
        ]);

        $order->createBackorder($order->orderLines());

        $this->orderRepository->save($order);

        $url = route('process-backorders');

        // When
        $this->get($url);

        // Then
        $foundOrder = $this->orderRepository->findOneByReferenceAndTenantId($order->reference(), $order->tenantId());

        self::assertEmpty($foundOrder->backorders());
        self::assertEquals($order->orderLines(), $order->picklists()->first()->orderLines());
    }
}
