<?php

namespace Tests\Unit\Warehouse\Infrastructure\Persistence\Eloquent\Repositories;

use App\Warehouse\Domain\Orders\Order;
use App\Warehouse\Domain\Services\InventoryServiceInterface;
use App\Warehouse\Infrastructure\Persistence\Eloquent\Repositories\EloquentOrderRepository;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Mockery\MockInterface;
use Tests\TestCase;

class EloquentOrderRepositoryTest extends TestCase
{
    use DatabaseMigrations;
    use RefreshDatabase;

    protected EloquentOrderRepository $orderRepository;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->orderRepository = new EloquentOrderRepository();
    }

    /** @test */
    public function it_should_add_an_order()
    {
        // Given
        $order = Order::factory()->make();

        // When
        $this->orderRepository->save($order);

        // Then
        $foundOrder = $this->orderRepository->findOneByReferenceAndTenantId($order->reference(), $order->tenantId());

        self::assertEquals($order, $foundOrder);
    }

    /** @test */
    public function it_should_add_multiple_orders()
    {
        // Given
        $tenantId = 1;
        $orders = Order::factory(10)->make([
            "tenant_id" => $tenantId
        ]);

        // When
        $this->orderRepository->saveMultiple($orders);

        // Then
        $foundOrders = $this->orderRepository->findAllByTenantId($tenantId);
        self::assertEquals($orders, $foundOrders);
    }

    /** @test */
    public function it_should_return_null_when_order_not_found()
    {
        // Given
        $reference = "Non Existing Reference";
        $tenantId = 999;

        // When
        $foundOrder = $this->orderRepository->findOneByReferenceAndTenantId($reference, $tenantId);

        // Then
        self::assertNull($foundOrder);
    }

    /** @test */
    public function it_should_remove_backorders_and_add_picklists()
    {
        // Given
        $inventoryServiceMock = $this->mock(InventoryServiceInterface::class, function (MockInterface $mock) {
            $mock->shouldReceive('getStock')
                ->andReturn(99999);
        });

        $this->app->bind(InventoryServiceInterface::class, function () use ($inventoryServiceMock) {return $inventoryServiceMock;});

        $order = Order::factory()->make([
            'tenant_id' => 1
        ]);

        $order->createBackorder($order->orderLines());
        $this->orderRepository->save($order);

        // When
        $order->processBackorders();
        $this->orderRepository->save($order);

        // Then
        $foundOrder = $this->orderRepository->findOneByReferenceAndTenantId($order->reference(), $order->tenantId());
        self::assertEquals($order, $foundOrder);
    }

    /** @test */
    public function it_should_update_order_with_picklist()
    {
        // Given
        $inventoryServiceMock = $this->mock(InventoryServiceInterface::class, function (MockInterface $mock) {
            $mock->shouldReceive('getStock')
                ->andReturn(99999);
        });

        $this->app->bind(InventoryServiceInterface::class, function () use ($inventoryServiceMock) {return $inventoryServiceMock;});

        $order = Order::factory()->make([
            'tenant_id' => 1
        ]);

        $this->orderRepository->save($order);

        // When
        $order->createPicklist($order->orderLines());
        $this->orderRepository->save($order);

        // Then
        $foundOrder = $this->orderRepository->findOneByReferenceAndTenantId($order->reference(), $order->tenantId());
        self::assertEquals($order, $foundOrder);
    }

    /** @test */
    public function it_should_update_processed_order_with_backorder()
    {
        // Given
        $inventoryServiceMock = $this->mock(InventoryServiceInterface::class, function (MockInterface $mock) {
            $mock->shouldReceive('getStock')
                ->andReturn(99999);
        });

        $this->app->bind(InventoryServiceInterface::class, function () use ($inventoryServiceMock) {return $inventoryServiceMock;});

        $order = Order::factory()->make([
            'tenant_id' => 1
        ]);

        $this->orderRepository->save($order);

        // When
        $order->createBackorder($order->orderLines());
        $this->orderRepository->save($order);

        // Then
        $foundOrder = $this->orderRepository->findOneByReferenceAndTenantId($order->reference(), $order->tenantId());
        self::assertEquals($order, $foundOrder);
    }
}
