openapi: 3.0.0
info:
  version: 1.0.0
  title: Headless-WMS API
  description: An API used for warehouse management

servers:
  - url: https://headless-wms.com/api/v1/

security:
  - bearerAuth: []

paths:
  /orders:
    get:
      tags:
        - Orders
      description: Get all the orders
      responses:
        '200':
          description: Successfully returned a list of orders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrderResponse'
        '400':
          $ref: '#/components/responses/400Error'
    post:
      tags:
        - Orders
      description: Create a new order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderBody'
      responses:
        '200':
          description: Successfully returned a list of orders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrderResponse'
        '400':
          $ref: '#/components/responses/400Error'

  /orders/{orderReference}:
    get:
      tags:
        - Orders
      description: Get order by order reference
      parameters:
        - name: orderReference
          in: path
          schema:
            type: string
          required: true
          example: "O231-29238"
      responses:
        '200':
          description: Successfully returned the order
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrderResponse'
        '404':
          description: Order with specified reference not found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrderResponse'
    put:
      tags:
        - Orders
      description: Update the order with specified order reference
      parameters:
        - name: orderReference
          in: path
          schema:
            type: string
          required: true
          example: "O231-29238"
      responses:
        '200':
          description: Successfully updated the order
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrderResponse'
        '404':
          description: Order with specified reference not found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrderResponse'
  /orders/{orderReference}/process:
    get:
      tags:
        - Orders
      description: Either generate picklists or backorders. When a picklist is created, stock mutations are being performed.
      parameters:
        - name: orderReference
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successfully processed the order
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrderResponse'
        '400':
          $ref: '#/components/responses/400Error'

  /orders/{orderReference}/picklists:
    get:
      tags:
        - Orders
      description: Returns the picklists for this order
      parameters:
        - name: orderReference
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successfully returns a list of picklists for order
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Picklist'
        '400':
          $ref: '#/components/responses/400Error'

  /orders/{orderReference}/backorders:
    get:
      tags:
        - Orders
      description: Returns the backorders for this order
      parameters:
        - name: orderReference
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successfully returns a list of backorders for order
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Backorder'
        '400':
          $ref: '#/components/responses/400Error'
  /picklists:
    get:
      tags:
        - Picklists
      description: Get all picklists
      responses:
        '200':
          description: Successfully returned a list of picklists
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Picklist'
        '400':
          $ref: '#/components/responses/400Error'

  /picklists/{picklistReference}:
    get:
      tags:
        - Picklists
      description: Get picklist by reference
      parameters:
        - name: picklistReference
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successfully returned the picklist
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Picklist'
        '400':
          $ref: '#/components/responses/400Error'

  /picklists/{picklistReference}/pick-all:
    post:
      tags:
        - Picklists
      description: Pick all products from picklist
      parameters:
        - name: picklistReference
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successfully picked all products from picklist
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Picklist'
        '400':
          $ref: '#/components/responses/400Error'

  /picklists/{picklistReference}/cancel:
    post:
      tags:
        - Picklists
      description: Cancels the picklist and rollback stock mutation
      parameters:
        - name: picklistReference
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successfully cancelled picklist
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Picklist'
        '400':
          $ref: '#/components/responses/400Error'


  /backorders:
    get:
      tags:
        - Backorders
      description: Get all backorders
      responses:
        '200':
          description: Successfully returned a list of backorders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Picklist'
        '400':
          $ref: '#/components/responses/400Error'

  /backorders/process:
    get:
      tags:
        - Backorders
      description: Process all backorders
      responses:
        '200':
          description: Successfully processed all backorders
        '400':
          $ref: '#/components/responses/400Error'

  /backorders/{backorderReference}/process:
    get:
      tags:
        - Backorders
      description: Process backorders with specific reference
      parameters:
        - name: backorderReference
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successfully processed backorder
        '400':
          $ref: '#/components/responses/400Error'
  /products:
    get:
      tags:
        - Products
      description: Get all products
      responses:
        '200':
          description: Successfully returned a list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '400':
          $ref: '#/components/responses/400Error'
    post:
      tags:
        - Products
      description: Create new product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '200':
          description: Successfully returned a list of products

        '400':
          $ref: '#/components/responses/400Error'

  /products/{productCode}/stock:
    get:
      tags:
        - Products
      description: Return product stock
      parameters:
        - name: productCode
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successfully returned the product stock
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '400':
          $ref: '#/components/responses/400Error'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    OrderResponse:
      type: object
      required:
        - id
      properties:
        reference:
          type: string
          example: "O120-1282"
        created_at:
          type: string
          format: date-time
          example: "2022-05-25 12:00:00"
        customer_number:
          type: string
          example: "K9172-82698"
        is_guest_order:
          type: boolean
          example: false
        order_lines:
          type: array
          items:
            type: object
            properties:
              product_code:
                type: string
                example: "P9812896"
              quantity:
                type: integer
                example: 99
    OrderBody:
      type: object
      required:
        - id
      properties:
        reference:
          type: string
          example: "O120-1282"
        customer_number:
          type: string
          example: "K9172-82698"
        is_guest_order:
          type: boolean
          example: false
        order_lines:
          type: array
          items:
            type: object
            properties:
              product_code:
                type: string
                example: "P9812896"
              quantity:
                type: integer
                example: 99
    OrderLine:
      type: object
      properties:
        product_code:
          type: string
          example: "P9812896"
        quantity:
          type: integer
          example: 99
    Product:
      type: object
      properties:
        product_code:
          type: string
          example: "P9812896"
        stock:
          type: array
          items:
            type: object
            properties:
              quantity:
                type: integer
                example: 88
    Customer:
      type: object
      required:
        - id
      properties:
        customer_number:
          type: string
          example: "K9172-82698"
        created_at:
          type: string
          format: date-time
          example: "2022-01-02 12:00:00"
        name:
          type: string
          example: "External Company X"
        contactName:
          type: string
          example: "John Doe"
        phoneNumbers:
          type: array
          items:
            type: string
            example: "+31672839004"
        email:
          type: string
          example: "johndoe@headless-wms.com"
        discount:
          type: number
          example: 10
        remarks:
          type: string
          example: "Deliver shipment around the corner"
        autoSplit:
          type: boolean
          example: true
        addresses:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                example: "External Company X"
              contactName:
                type: string
                example: "John Doe"
              addressLine1:
                type: string
                example: "Leeghwaterstraat 32"
              addressLine2:
                type: string
                example: "Leeghwaterstraat 46"
              zipcode:
                type: string
                example: "2654ES"
              city:
                type: string
                example: "Rotterdam"
              region:
                type: string
                example: "Zuid-Holland"
              countryCode:
                type: string
                example: "NL"
              defaultInvoice:
                type: boolean
                example: true
              defaultDelivery:
                type: boolean
                example: false
    Picklist:
      type: object
      required:
        - id
      properties:
        reference:
          type: string
          example: "P120-1282"
        created_at:
          type: string
          format: date-time
          example: "2022-05-25 12:00:00"
        order_reference:
          type: string
          example: "O9172-82698"
        order_lines:
          type: array
          items:
            type: object
            properties:
              product_code:
                type: string
                example: "P9812896"
              quantity:
                type: integer
                example: 99

    Shipment:
      type: object
      required:
        - id
      properties:
        reference:
          type: string
          example: "S120-1282"
        created_at:
          type: string
          format: date-time
          example: "2022-05-25 12:00:00"
        picklist_reference:
          type: string
          example: "P9172-82698"

    Warehouse:
      type: object
      required:
        - id
      properties:
        id:
          type: string
          example: "W-123"
        created_at:
          type: string
          format: date-time
          example: "2022-05-25 12:00:00"
        name:
          type: string
          example: "Main Warehouse"

    Backorder:
      type: object
      required:
        - id
      properties:
        reference:
          type: string
          example: "P120-1282"
        created_at:
          type: string
          format: date-time
          example: "2022-05-25 12:00:00"
        order_reference:
          type: string
          example: "O9172-82698"
        order_lines:
          type: array
          items:
            type: object
            properties:
              product_code:
                type: string
                example: "P9812896"
              quantity:
                type: integer
                example: 99

  parameters:
    PageLimit:
      name: limit
      in: query
      description: Limits the number of items on a page
      schema:
        type: integer

    PageOffset:
      name: offset
      in: query
      description: Specifies the page number to be displayed
      schema:
        type: integer

    SinceDate:
      name: since
      in: query
      description: Filter out the objects before this date and time [YYYY-mm-dd]
      schema:
        type: string
        format: date-time
      example: "2022-12-30"

    UntilDate:
      name: until
      in: query
      description: Filter out the objects after this date and time [YYYY-mm-dd]
      schema:
        type: string
        format: date-time
      example: "2022-01-01"

    OrderState:
      name: state
      in: query
      description: Only get the orders with specific state
      schema:
        type: string
        enum:
          - "unprocessed"
          - "processed"
          - "shipped"
          - "cancelled"
      example: "processed"
  responses:
    400Error:
      description: Invalid request
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
    404Error:
      description: Resource not found
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
