<?php

namespace Tests\Unit\Inventory\Infrastructure\Persistence\InMemory\Repositories;

use App\Inventory\Domain\Products\Product;
use App\Inventory\Infrastructure\Persistence\InMemory\Repositories\InMemoryCollectionProductRepository;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Tests\TestCase;

/**
 * @property InMemoryCollectionProductRepository $productRepository
 */
class InMemoryCollectionProductRepositoryTest extends TestCase
{
    use DatabaseMigrations;

    protected int $tenantId;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->productRepository = new InMemoryCollectionProductRepository();

        $user = \App\Models\User::factory()->create();
        $this->tenantId = $user->tenant->id;
    }

    /** @test */
    public function it_should_add_product()
    {
        // Given
        $productCode = "Test Product Code";
        $stock = 10;
        $product = Product::factory()->make([
            'product_code' => $productCode,
            'stock' => $stock,
            'tenant_id' => $this->tenantId
        ]);

        // When
        $this->productRepository->save($product);

        // Then
        $foundProduct = $this->productRepository->findByProductCodeAndTenantId($product->productCode(), $this->tenantId);
        self::assertEquals($product, $foundProduct);
    }

    /** @test */
    public function it_should_decrease_stock()
    {
        // Given
        $productCode = "Test Product Code";
        $stock = 10;
        $product = Product::factory()->make([
            'product_code' => $productCode,
            'stock' => $stock,
            'tenant_id' => $this->tenantId
        ]);

        $this->productRepository->save($product);
        $decreaseAmount = 1;

        // When
        $this->productRepository->decreaseStock($productCode, $decreaseAmount, $this->tenantId);

        // Then
        $foundProduct = $this->productRepository->findByProductCodeAndTenantId($product->productCode(), $this->tenantId);
        self::assertEquals($stock - $decreaseAmount, $foundProduct->stock());
    }

    /** @test */
    public function it_should_increase_stock()
    {
        // Given
        $productCode = "Test Product Code";
        $stock = 10;
        $product = Product::factory()->make([
            'product_code' => $productCode,
            'stock' => $stock,
            'tenant_id' => $this->tenantId
        ]);
        $this->productRepository->save($product);
        $increaseAmount = 1;

        // When
        $this->productRepository->increaseStock($productCode, $increaseAmount, $this->tenantId);

        // Then
        $foundProduct = $this->productRepository->findByProductCodeAndTenantId($product->productCode(), $this->tenantId);
        self::assertEquals($stock + $increaseAmount, $foundProduct->stock());
    }

    /** @test */
    public function it_should_get_the_product_stock()
    {
        // Given
        $productCode = "Test Product Code";
        $stock = 10;
        $product = Product::factory()->make([
            'product_code' => $productCode,
            'stock' => $stock,
            'tenant_id' => $this->tenantId
        ]);
        $this->productRepository->save($product);

        // When
        $foundStock = $this->productRepository->getStock($productCode, $this->tenantId);

        // Then
        self::assertEquals($stock, $foundStock);
    }

    /** @test */
    public function it_should_update_the_product_stock()
    {
        // Given
        $productCode = "Test Product Code";
        $stock = 10;
        $product = Product::factory()->make([
            'product_code' => $productCode,
            'stock' => $stock,
            'tenant_id' => $this->tenantId
        ]);
        $this->productRepository->save($product);
        $updatedStock = 5;

        // When
        $updatedProduct = $this->productRepository->updateStock($productCode, $updatedStock, $this->tenantId);

        // Then
        self::assertEquals($stock - $updatedStock, $updatedProduct->stock());
    }
}
