<?php

namespace Tests\Feature\Inventory;

use App\Inventory\Domain\Products\Product;
use App\Inventory\Domain\Repositories\ProductRepositoryInterface;
use App\Models\User;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Mockery\MockInterface;
use Tests\TestCase;

class ChangeProductStockTest extends TestCase
{
    use DatabaseMigrations;

    protected int $tenantId;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $user = User::factory()->create();
        $this->actingAs($user);
        $this->tenantId = $user->tenant->id;
    }

    /** @test */
    public function it_should_increase_product_stock()
    {
        $this->withoutExceptionHandling();

        // Given
        $productCode = "Test Product Code";
        $quantity = 10;
        $stock = 10;

        $productRepositoryMock = $this->mock(ProductRepositoryInterface::class, function (MockInterface $mock) use ($productCode, $stock, $quantity){
            $mock->shouldReceive("increaseStock")
                ->once()
                ->andReturn(Product::factory()->make([
                    'product_code' => $productCode,
                    'stock' => $stock + $quantity,
                    'tenant_id' => $this->tenantId
                ]));
        });

        $this->app->instance(ProductRepositoryInterface::class, $productRepositoryMock);

        $url = route('change-product-stock', [
            "productCode" => $productCode,
        ]);

        // When
        $response = $this->post($url, [
            "adjust_by" => $quantity
        ]);

        // Then
        $response->assertJson([
            "data" => [
                "stock" => $stock + $quantity
            ]
        ]);
    }

    /** @test */
    public function it_should_decrease_product_stock()
    {
        $this->withoutExceptionHandling();

        // Given
        $productCode = "Test Product Code";
        $quantity = -10;
        $stock = 10;

        $productRepositoryMock = $this->mock(ProductRepositoryInterface::class, function (MockInterface $mock) use ($productCode, $stock, $quantity){
            $mock->shouldReceive("decreaseStock")
                ->once()
                ->andReturn(Product::factory()->make([
                    'product_code' => $productCode,
                    'stock' => 0
                ]));
        });

        $this->app->instance(ProductRepositoryInterface::class, $productRepositoryMock);

        $url = route('change-product-stock', [
            "productCode" => $productCode,
        ]);

        // When
        $response = $this->post($url, [
            "adjust_by" => $quantity
        ]);

        // Then
        $response->assertJson([
            "data" => [
                "product_code" => $productCode,
                "stock" => 0
            ]
        ]);
    }

    /** @test */
    public function it_should_change_product_stock_to_specified_value()
    {
        $this->withoutExceptionHandling();

        // Given
        $productCode = "Test Product Code";
        $quantity = 20;

        $productRepositoryMock = $this->mock(ProductRepositoryInterface::class, function (MockInterface $mock) use ($productCode, $quantity){
            $mock->shouldReceive("updateStock")
                ->once()
                ->andReturn(Product::factory()->make([
                    'product_code' => $productCode,
                    'stock' => $quantity,
                    'tenant_id' => $this->tenantId
                ]));
        });

        $this->app->instance(ProductRepositoryInterface::class, $productRepositoryMock);

        $url = route('change-product-stock', [
            "productCode" => $productCode,
        ]);

        // When
        $response = $this->post($url, [
            "update_with" => $quantity
        ]);

        // Then
        $response->assertJson([
            "data" => [
                "product_code" => $productCode,
                "stock" => $quantity
            ]
        ]);
    }

    /** @test */
    public function it_should_throw_exception_when_adjust_to_and_set_quantity_are_both_not_null()
    {
        $this->withoutExceptionHandling();

        // Given
        $productCode = "Test Product Code";
        $quantity = 20;

        $productRepositoryMock = $this->mock(ProductRepositoryInterface::class);
        $this->app->instance(ProductRepositoryInterface::class, $productRepositoryMock);

        $url = route('change-product-stock', [
            "productCode" => $productCode,
        ]);

        // When
        $response = $this->post($url, [
            "update_with" => $quantity,
            "adjust_by" => $quantity
        ]);

        // Then
        $response->assertJson([
            "error" => [
                "code" => "500",
                "message" => "Specify either adjust_by or update_with, not both"
            ]
        ]);
    }

    /** @test */
    public function it_should_throw_exception_when_adjust_to_and_set_quantity_are_both_null()
    {
        $this->withoutExceptionHandling();

        // Given
        $productCode = "Test Product Code";
        $quantity = null;

        $productRepositoryMock = $this->mock(ProductRepositoryInterface::class);
        $this->app->instance(ProductRepositoryInterface::class, $productRepositoryMock);

        $url = route('change-product-stock', [
            "productCode" => $productCode,
        ]);

        // When
        $response = $this->post($url, [
            "update_with" => $quantity,
            "adjust_by" => $quantity
        ]);

        // Then
        $response->assertJson([
            "error" => [
                "code" => "500",
                "message" => "You should either specify adjust_by or update_with"
            ]
        ]);
    }
}
