<?php

namespace Tests\Feature\Inventory;

use App\Inventory\Domain\Products\Product;
use App\Inventory\Domain\Repositories\ProductRepositoryInterface;
use App\Inventory\Infrastructure\Persistence\InMemory\Repositories\InMemoryCollectionProductRepository;
use App\Models\User;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Tests\TestCase;

class CreateProductTest extends TestCase
{
    use DatabaseMigrations;

    protected int $tenantId;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $user = User::factory()->create();
        $this->actingAs($user);
        $this->tenantId = $user->tenant->id;
    }

    /** @test */
    public function it_should_create_product()
    {
        $this->withoutExceptionHandling();

        // Given
        $productCode = "Test Product Code";
        $stock = 10;
        $product = Product::factory()->make([
            'product_code' => $productCode,
            'stock' => $stock,
            'tenant_id' => $this->tenantId
        ]);

        $url = route('create-product');

        $productRepository = new InMemoryCollectionProductRepository();
        $this->app->instance(ProductRepositoryInterface::class, $productRepository);

        // When
        $response = $this->post($url, [
            "product" => $product->toArray()
        ]);

        // Then
        $response->assertJson([
            "data" => null,
        ]);

        $foundProduct = $productRepository->findByProductCodeAndTenantId($productCode, $this->tenantId);
        self::assertEquals($product, $foundProduct);
    }

    /** @test */
    public function it_should_return_error_when_product_already_exists()
    {
        $this->withoutExceptionHandling();

        // Given
        $productCode = "Test Product Code";
        $stock = 10;
        $product = Product::factory()->make([
            'product_code' => $productCode,
            'stock' => $stock,
            'tenant_id' => $this->tenantId
        ]);

        $url = route('create-product');

        $productRepository = new InMemoryCollectionProductRepository();
        $productRepository->save($product);

        $this->app->instance(ProductRepositoryInterface::class, $productRepository);

        // When
        $response = $this->post($url, [
            "product" => $product->toArray()
        ]);

        // Then
        $response->assertJson([
            "data" => null,
            "error" => [
                'message' => "Product with product code " . $productCode . " already exists"
            ],
        ]);

        $foundProduct = $productRepository->findByProductCodeAndTenantId($productCode, $this->tenantId);
        self::assertEquals($product, $foundProduct);
    }
}
