<?php

namespace Tests\Feature\Inventory;

use App\Inventory\Domain\Products\Product;
use App\Inventory\Domain\Repositories\ProductRepositoryInterface;
use App\Inventory\Infrastructure\Persistence\InMemory\Repositories\InMemoryCollectionProductRepository;
use App\Models\User;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class GetAllProductsTest extends TestCase
{
    use DatabaseMigrations;
    use RefreshDatabase;

    protected InMemoryCollectionProductRepository $productRepository;
    protected int $tenantId;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->productRepository = new InMemoryCollectionProductRepository();
        $this->app->bind(ProductRepositoryInterface::class, function () {return $this->productRepository;});

        $user = User::factory()->create();
        $this->tenantId = $user->tenant_id;
        $this->actingAs($user);
    }

    /** @test */
    public function it_should_return_all_products_for_tenant()
    {
        // Given
        $products = Product::factory(100)->make([
            'tenant_id' => $this->tenantId
        ]);

        $this->productRepository->saveMultiple($products);

        $url = route('get-all-products');

        // When
        $response = $this->get($url);

        // Then
        $response->assertJson([
            'data' => [
                'products' => $products->toArray()
            ]
        ]);
    }

    /** @test */
    public function it_should_not_return_products_of_other_tenant()
    {
        // Given

        $products = Product::factory(100)->make([
            'tenant_id' => $this->tenantId
        ]);

        $productsFromOtherTenant = Product::factory(100)->make([
            'tenant_id' => $this->tenantId + 1
        ]);

        $this->productRepository->saveMultiple($products);
        $this->productRepository->saveMultiple($productsFromOtherTenant);

        $url = route('get-all-products');

        // When
        $response = $this->get($url);

        // Then
        $response->assertJson([
            'data' => [
                'products' => $products->toArray()
            ]
        ]);
    }
}
