<?php

namespace Tests\Feature\Inventory;

use App\Inventory\Domain\Products\Product;
use App\Inventory\Domain\Repositories\ProductRepositoryInterface;
use App\Models\User;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Mockery\MockInterface;
use Tests\TestCase;

class GetProductStockTest extends TestCase
{
    use DatabaseMigrations;

    protected int $tenantId;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $user = User::factory()->create();
        $this->tenantId = $user->tenant->id;
        $this->actingAs($user);
    }

    /** @test */
    public function it_should_get_product_stock()
    {
        $this->withoutExceptionHandling();

        // Given
        $productCode = "Test Product Code";
        $stock = 10;
        $product = Product::factory()->make([
            'product_code' => $productCode,
            'stock' => $stock,
            'tenant_id' => $this->tenantId
        ]);
        $url = route('get-product-stock', [
            "productCode" => $productCode
        ]);

        $productRepositoryMock = $mock = $this->mock(ProductRepositoryInterface::class, function (MockInterface $mock) use ($product) {
            $mock->shouldReceive('findByProductCodeAndTenantId')
                ->once()
                ->andReturn($product);
        });

        $this->app->instance(ProductRepositoryInterface::class, $productRepositoryMock);

        // When
        $response = $this->get($url);

        // Then
        $response->assertJson([
            "data" => [
                "product" => [
                    "product_code" => $productCode,
                    "stock" => $stock
                ]
            ]
        ]);
    }

    /** @test */
    public function it_should_return_error_when_product_does_not_exist()
    {
        $this->withoutExceptionHandling();

        // Given
        $productCode = "Test Product Code";
        $url = route('get-product-stock', [
            "productCode" => $productCode
        ]);

        $productRepositoryMock = $mock = $this->mock(ProductRepositoryInterface::class, function (MockInterface $mock) use ($productCode) {
            $mock->shouldReceive('findByProductCodeAndTenantId')
                ->once()
                ->andReturn(null);
        });

        $this->app->instance(ProductRepositoryInterface::class, $productRepositoryMock);

        // When
        $response = $this->get($url);

        // Then
        $response->assertJson([
            "error" => [
                "code" => "500",
                "message" => "Product with product code " . $productCode . " not found"
            ]
        ]);
    }
}
