<?php

namespace Tests\Unit\Warehouse;

use App\Warehouse\Domain\Orders\Order;
use App\Warehouse\Infrastructure\Persistence\InMemory\Repositories\InMemoryCollectionOrderRepository;
use Eris\Generators;
use Tests\TestCase;

class InMemoryCollectionOrderRepositoryTest extends TestCase
{
    use \Eris\TestTrait;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->orderRepository = new InMemoryCollectionOrderRepository();
    }

    /** @test */
    public function it_should_return_order_with_reference_from_tenant()
    {
        // Given
        $tenantId = 1;
        $order = Order::factory()->make([
            "tenant_id" => $tenantId
        ]);
        $this->orderRepository->save($order);

        // When
        $foundOrder = $this->orderRepository->findOneByReferenceAndTenantId($order->reference(), $tenantId);

        // Then
        self::assertEquals($order, $foundOrder);
    }

    /** @test */
    public function it_should_add_multiple_orders()
    {
        $tenantId = 1;

        $this->forAll(
            Generators::choose(2, 1000)
        )
        ->then(function (int $amountOfOrders) use ($tenantId) {
            $orderRepository = new InMemoryCollectionOrderRepository();
            $orders = Order::factory($amountOfOrders)->make([
                "tenant_id" => $tenantId
            ]);
            $orderRepository->saveMultiple($orders);
            $this->assertEquals($amountOfOrders, $orderRepository->findAllByTenantId($tenantId)->count());
        });
    }

    /** @test */
    public function it_should_get_all_orders_from_tenant()
    {
        // Given
        $tenantId = 1;

        $ordersFromTenant = Order::factory(100)->make([
            "tenant_id" => $tenantId
        ]);

        $ordersNotFromTenant = Order::factory(100)->make([
            "tenant_id" => $tenantId + 1
        ]);

        $this->orderRepository->saveMultiple($ordersFromTenant);
        $this->orderRepository->saveMultiple($ordersNotFromTenant);

        // When
        $foundOrdersFromTenant = $this->orderRepository->findAllByTenantId($tenantId);

        // Then
        self::assertEquals($ordersFromTenant, $foundOrdersFromTenant);
    }
}
