<?php

namespace Tests\Unit\Inventory\Infrastructure\Persistence\Eloquent\Repositories;

use App\Inventory\Domain\Products\Product;
use App\Inventory\Infrastructure\Persistence\Eloquent\Repositories\EloquentProductRepository;
use App\Models\User;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * @property EloquentProductRepository $productRepository
 */
class EloquentProductRepositoryTest extends TestCase
{
    use DatabaseMigrations;
    use RefreshDatabase;

    protected int $tenantId;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->productRepository = new EloquentProductRepository();
        $user = User::factory()->create();
        $this->actingAs($user);
        $this->tenantId = $user->tenant->id;
    }

    /** @test */
    public function it_should_add_a_product()
    {
        // Given
        $product = Product::factory()->make([
            'product_code' => 'Test Product Code',
            'stock' => 10,
            'tenant_id' => $this->tenantId
        ]);

        // When
        $this->productRepository->save($product);

        // Then
        $foundProduct = $this->productRepository->findByProductCodeAndTenantId($product->productCode(), $this->tenantId);
        self::assertEquals($product, $foundProduct);
    }

    /** @test */
    public function it_should_decrease_the_stock()
    {
        // Given
        $product = Product::factory()->make([
            'product_code' => 'Test Product Code',
            'stock' => 10,
            'tenant_id' => $this->tenantId
        ]);
        $decreaseQuantity = 5;
        $this->productRepository->save($product);

        // When
        $decreasedStockProduct = $this->productRepository->decreaseStock($product->productCode(), $decreaseQuantity, $this->tenantId);

        // Then
        self::assertEquals(5, $decreasedStockProduct->stock());
    }

    /** @test */
    public function it_should_increase_the_stock()
    {
        // Given
        $product = Product::factory()->make([
            'product_code' => 'Test Product Code',
            'stock' => 10
        ]);
        $increaseQuantity = 5;
        $this->productRepository->save($product);

        // When
        $decreasedStockProduct = $this->productRepository->increaseStock($product->productCode(), $increaseQuantity, $this->tenantId);

        // Then
        $stock = $this->productRepository->getStock($product->productCode(), $this->tenantId);
        self::assertEquals(15, $stock);
    }

    /** @test */
    public function it_should_update_the_stock()
    {
        $product = Product::factory()->make([
            'product_code' => 'Test Product Code',
            'stock' => 10
        ]);
        $updateQuantity = 5;
        $this->productRepository->save($product);

        // When
        $decreasedStockProduct = $this->productRepository->updateStock($product->productCode(), $updateQuantity, $this->tenantId);

        // Then
        $stock = $this->productRepository->getStock($product->productCode(), $this->tenantId);
        self::assertEquals(5, $stock);
    }

    /** @test */
    public function it_should_not_return_products_of_other_tenants()
    {
        $products = Product::factory(100)->make([
            'tenant_id' => $this->tenantId
        ]);

        $productsFromOtherTenant = Product::factory(100)->make([
            'tenant_id' => $this->tenantId + 1
        ]);

        $this->productRepository->saveMultiple($products);
        $this->productRepository->saveMultiple($productsFromOtherTenant);

        // When
        $foundProducts = $this->productRepository->findAllByTenantId($this->tenantId);

        // Then
        self::assertEquals($products, $foundProducts);
    }
}
