<?php

namespace Tests\Unit\Warehouse\Orders;

use App\Warehouse\Domain\Exceptions\NonGuestOrderWithoutCustomerNumberException;
use App\Warehouse\Domain\Orders\Order;
use App\Warehouse\Domain\Orders\OrderLine;
use App\Warehouse\Domain\Products\Product;
use App\Warehouse\Domain\Services\InventoryServiceInterface;
use Mockery\MockInterface;
use Tests\TestCase;


class OrderTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /** @test */
    public function it_should_have_a_reference()
    {
        // Given
        $order = Order::factory()->make();

        // When
        $reference = $order->reference();

        // Then
        self::assertNotNull($reference);
    }

    /** @test */
    public function it_should_have_order_lines()
    {
        // Given
        $order = Order::factory()->make();

        // When
        $orderLines = $order->orderLines();

        // Then
        self::assertNotNull($orderLines);
    }

    /** @test */
    public function it_should_have_a_customer_number()
    {
        // Given
        $order = Order::factory()->make();

        // When
        $customerNumber = $order->customerNumber();

        // Then
        self::assertNotNull($customerNumber);
    }

    /** @test */
    public function it_should_show_if_order_is_guest_order()
    {
        // Given
        $order = Order::factory()->make();

        // When
        $isGuestOrder = $order->isGuestOrder();

        // Then
        self::assertNotNull($isGuestOrder);
    }

    /** @test */
    public function it_should_throw_exception_when_order_is_no_guest_order_and_customer_number_is_not_set()
    {
        // Assert
        $this->expectException(NonGuestOrderWithoutCustomerNumberException::class);

        // When
        $order = Order::factory()->make(([
            "customer_number" => null,
            "is_guest_order" => false
        ]));
    }

    /** @test */
    public function it_should_have_a_tenant_id()
    {
        // Given
        $order = Order::factory()->make();

        // When
        $tenantId = $order->tenantId();

        // Then
        self::assertNotNull($tenantId);
    }

    /** @test */
    public function it_should_rollback_stock_deduction_when_cancelling_picklist()
    {
        // Given
        $productCode = 'Test Product Code';
        $quantity = 10;
        $tenantId = 1;
        $inventoryServiceMock = $this->mock(InventoryServiceInterface::class, function (MockInterface $mock) use($productCode, $quantity, $tenantId) {
            $mock->shouldReceive('adjustStock')
                ->once()
                ->with($productCode, $quantity, $tenantId);
        });

        $this->app->bind(InventoryServiceInterface::class, function () use ($inventoryServiceMock) {return $inventoryServiceMock;});

        $orderLine = new OrderLine(new Product($productCode), $quantity);
        $order = Order::factory()->make([
            'order_lines' => collect([$orderLine]),
            'tenant_id' => $tenantId
        ]);

        $picklist = $order->createPicklist($order->orderLines());

        // When
        $order->cancelPicklist($picklist->reference());

        // Then

    }
}
