<?php

namespace Unit\Warehouse\Infrastructure\Services;

use App\Inventory\Domain\Products\Product;
use App\Inventory\Domain\Repositories\ProductRepositoryInterface;
use App\Inventory\Infrastructure\Persistence\InMemory\Repositories\InMemoryCollectionProductRepository;
use App\Warehouse\Infrastructure\Services\InventoryService;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Tests\TestCase;

class InventoryServiceTest extends TestCase
{
    use DatabaseMigrations;

    protected InventoryService $inventoryService;
    protected InMemoryCollectionProductRepository $productRepository;
    protected int $tenantId;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->productRepository = new InMemoryCollectionProductRepository();
        $this->app->bind(ProductRepositoryInterface::class, function () {return $this->productRepository;});
        $this->inventoryService = new InventoryService();

        $user = \App\Models\User::factory()->create();
        $this->actingAs($user);
        $this->tenantId = $user->tenant->id;
    }

    /** @test */
    public function it_should_return_product_stock()
    {
        // Given
        $productCode = "Test Product Code";
        $stock = 10;
        $product = Product::factory()->make([
            'product_code' => $productCode,
            'stock' => $stock,
            'tenant_id' => $this->tenantId
        ]);
        $this->productRepository->save($product);

        // When
        $foundStock = $this->inventoryService->getStock($productCode, $this->tenantId);

        // Then
        self::assertEquals($stock, $foundStock);
    }

    /** @test */
    public function it_should_adjust_product_stock()
    {
        $productCode = "Test Product Code";
        $stock = 10;
        $product = Product::factory()->make([
            'product_code' => $productCode,
            'stock' => $stock,
            'tenant_id' => $this->tenantId
        ]);
        $adjustStockBy = -5;
        $this->productRepository->save($product);

        // When
        $foundStock = $this->inventoryService->adjustStock($productCode, $adjustStockBy, $this->tenantId);

        // Then
        self::assertEquals($stock + $adjustStockBy, $foundStock);
    }
}
